# About {.unnumbered}

## Date {.unnumbered}

19 November 2024 | 08h30 - 13h00

## Abstract {.unnumbered}

Geospatial networks are graphs embedded in geographical space. That means that both the nodes and edges in the graph can be represented as geographic features (e.g. points and lines) with a location somewhere on or near the surface of the earth. They play an important role in many different domains, ranging from transportation planning and logistics to ecology and epidemiology. The structure and characteristics of geospatial networks go beyond standard graph topology, and therefore it is crucial to explicitly take space into account when analyzing them. The R package sfnetworks is created to facilitate such an integrated workflow. It combines the forces of two popular R packages, sf for spatial data science and tidygraph for standard graph analysis, and extends them with functionalities that are specific to geospatial network analysis, such as geographic shortest path calculations, geospatial network cleaning, and topology modification. It also facilitates smooth integration with packages for statistical analysis on spatial linear networks, and is designed to seamlessly fit into tidy data wrangling workflows. This workshop provides an introduction to the sfnetworks package for geospatial network analysis. We will start with simple examples on abstract dummy networks, and gradually move towards the analysis of real-world networks that we extract from OpenStreetMap. We will prepare several analytical tasks to solve, of varying difficulty. If you are already working with geospatial networks, you are also encouraged to bring your own use-cases.

## Pre-requisites

### R and RStudio installation

A working installation of:

- R (follow [CRAN recommendations](https://cran.r-project.org/) for your set-up).
- RStudio (>= 2024.04.x with Quarto) see [here](https://posit.co/download/rstudio-desktop/).

### R packages

Please run those commands inside the R console:

```r
# Install the remotes package from CRAN Repo
install.packages(remotes)

# Install workshop and its dependencies
remotes::install_github("luukvdmeer/sfnetworks-workshop")
```

You can follow along in your own R script, or [clone the repository](https://github.com/luukvdmeer/sfnetworks-workshop) to run the Quarto documents interactively.
